# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r requirements_mongodb.txt"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "uvicorn app_with_mongodb:app --host 0.0.0.0 --port $PORT"
