# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r requirements_mongodb.txt"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "python app_with_mongodb.py"
