# Railway deployment configuration for Pravha Backend

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python3 app_with_mongodb.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.13"
PORT = "8002"
MONGODB_URL = "${{MONGODB_URL}}"
SECRET_KEY = "${{SECRET_KEY}}"
ENVIRONMENT = "production"
