# Railway deployment configuration
[build]
builder = "dockerfile"

[deploy]
startCommand = "python app_with_mongodb.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"