# Railway deployment configuration for Pravha Backend
[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements_mongodb.txt"

[deploy]
startCommand = "uvicorn app_with_mongodb:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"