name: pravha-backend
services:
- name: api
  source_dir: /backend
  github:
    repo: your-username/your-repo-name
    branch: main
  run_command: gunicorn app_with_mongodb:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: SECRET_KEY
    value: your-production-secret-key-change-this
  - key: MONGODB_URI
    value: mongodb+srv://username:password@cluster.mongodb.net/pravha_flood_management
  - key: GMAIL_EMAIL
    value: your-email@gmail.com
  - key: GMAIL_PASSWORD
    value: your-app-password
